### ISSUE TITLE
Upgrade installed?

### ISSUE THREAD

**Issue by wamatt** [mkalmes/brewupdate#11]
How easy would it be to allow upgrading of installed packages?

**Comment by mkalmes** [comment]
It's easy to add this functionality. Nonetheless I will not add this behavior to avoid side effects.

If you automate the installation of a package changes are high that you miss some important informations regarding this package (e.g. new dependencies or problems with other software). I would advise against automatic installation but if you insist, take a look at [this fork](https://github.com/cgswong/brewupdate/).

**Comment by wamatt** [comment]
Thanks! The concerns you raised make sense, and I do have them too. However that's also what log files are for. 

I'd consider Chrome important software too, and don't mind it autoupdating. Updating also can fix vulnerabilities, but as you say introduces the prospect of things breaking.

I'm going to try it out for a few months, and see how it goes. If it's a pain it's easy to switch back.

**Comment by wamatt** [comment]
In an ideal system any new breakage or important info should notify the user. Whereas most of the time routine upgrading would occur silently and automatically.
