### ISSUE TITLE
Probably should only be happening when connected to network

### ISSUE THREAD

**Issue by szhu** [mkalmes/brewupdate#4]
From [`man launchd.plist`](https://developer.apple.com/library/mac/documentation/Darwin/Reference/Manpages/man5/launchd.plist.5.html):

>  **KeepAlive &lt;boolean or dictionary of stuff>**
> **NetworkState &lt;boolean>**
> If true, the job will be kept alive as long as the network is up, where up is defined as at least one non-loopback interface being up and having IPv4 or IPv6 addresses assigned to them.  If false, the job will be kept alive in the inverse condition.

**Comment by mkalmes** [comment]
This keeps `brewupdate` running in an endless loop.

**Comment by szhu** [comment]
What if `SuccessfulExit=false` is added as well?

**Comment by mkalmes** [comment]
Quote from the man-page (emphasis is mine):

> This optional key is used to control whether your job is to be _kept continuously running_ […]

I thought about your suggestion for a while and I think that `KeepAlive` shouldn't be used for this. If the network is down `brew update` will just timeout.

Do I miss something obvious? :)

**Comment by szhu** [comment]
I'll look into whether `KeepAlive` is the right setting for this improvement, but the reason for having this improvement at all is simply that if the computer is always on but never online at 11am, `brewupdate` essentially does nothing.
