### ISSUE TITLE
Suggestion: display output to a widget in notification center (OS X Yosemite)

### ISSUE THREAD

**Issue by jancbeck** [mkalmes/brewupdate#6]
It would be great if there was a more obvious place where available updates are displayed. Checking Console.app everyday is no improvement over manually fetching formulae to me.

I'm no OS X developer (yet) but [terminal-notifier](https://github.com/alloy/terminal-notifier) looks promising:

> terminal-notifier is a command-line tool to send Mac OS X User Notifications, which are available in Mac OS X 10.8 and higher.

And then there is also a way to send notifications via AppleScript:
https://apple.stackexchange.com/questions/57412/how-can-i-trigger-a-notification-center-notification-from-an-applescript-or-shel

Would be great to have this implemented in brewupdate.

**Comment by heitortsergent** [comment]
@jancbeck I made some changes to the script here https://github.com/heitortsergent/brewupdate/, don't know if it's exactly what are you looking for, now terminal-notifier shows a notification when the script runs.

Also added logs like @szhu mentioned in #5.

**Comment by jancbeck** [comment]
thanks @heitortsergent, sounds exactly what I wanted. I'll check it out.

**Comment by mkalmes** [comment]
`brewupdate` is designed to automate the updating of your formulae (like `softwareupdate` or `portsnap`).

I intend to add a second agent just for outputting the state of formulae (see #10 for a rough idea). With the help of such an agent you could pipe the output to any program you like for further processing.
